name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to VPS
      run: |
        ssh deploy@your-vps-ip << 'EOF'
          set -e
          # Load rbenv
          export RBENV_ROOT="$HOME/.rbenv"
          export PATH="$RBENV_ROOT/bin:$PATH"
          eval "$(rbenv init -)"
          
          # Navigate to the app and deploy
          cd ~/app_dev/HalalBytes/
          git pull origin main
          bundle install --deployment --without development test
          bundle exec rake db:migrate RAILS_ENV=production
          bundle exec rake assets:precompile RAILS_ENV=production
          sudo service nginx restart
        EOF
