name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            # Load rbenv
            export RBENV_ROOT="$HOME/.rbenv"
            export PATH="$RBENV_ROOT/bin:$PATH"
            eval "$(rbenv init -)"

            # Navigate to the app and deploy
            cd ~/app_dev/HalalBytes/
            git pull origin main

            # Set the RAILS_MASTER_KEY environment variable for credentials decryption (if using credentials)
            export RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
            
            # Set environment variables for database connection
            export DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            export DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            export DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            
            bundle install --deployment --without development test
            bundle exec rake assets:clobber RAILS_ENV=production
            bundle exec rake db:migrate RAILS_ENV=production
            bundle exec rake assets:precompile RAILS_ENV=production
            touch tmp/restart.txt
            sudo service nginx restart
